<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_U_os_username</name>
   <tag></tag>
   <elementGuidId>4b0ec72c-9aeb-41d7-96cf-9f284bb21396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-form-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-form-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de9adbb0-7010-4ec4-ad90-400ebb4db7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text medium-field focus-visible</value>
      <webElementGuid>c98ca1e9-1df9-4000-b5c2-9fa3017802c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-form-username</value>
      <webElementGuid>774e9677-1c83-451e-ac07-cb4da886da9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>os_username</value>
      <webElementGuid>d40d33cd-c552-4fb5-b608-bc491c7fb6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d8522d6-78e0-472e-ad89-8df6743bb588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form-username&quot;)</value>
      <webElementGuid>02372c51-2c1c-4f0c-8c60-649f11ed3bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-form-username']</value>
      <webElementGuid>c9ddb678-f0e6-4a89-b307-888a6269bd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginform']/div/input</value>
      <webElementGuid>0e6a24d2-4206-486a-8198-78321641cbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div/input</value>
      <webElementGuid>ced2e64c-e2db-47e2-9178-57fb9d2fb29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-form-username' and @name = 'os_username' and @type = 'text']</value>
      <webElementGuid>e7ab5d8f-e64c-45b5-8a5b-41ff8769019f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
