<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Diagram</name>
   <tag></tag>
   <elementGuidId>c0442085-f2f4-42cd-bb61-edab5130d3f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflow-diagram</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='workflow-diagram']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba73ebcb-bf48-452d-885b-b41ca55866e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aui-button workflow-edit-toggle</value>
      <webElementGuid>6da522bf-5b41-42ec-9a1f-ad0158b7ef42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflow-diagram</value>
      <webElementGuid>388eae97-303a-49d2-81ae-caabe7ff2c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/secure/admin/workflows/WorkflowDesigner.jspa?wfName=Software+Simplified+Workflow+for+Project+POK&amp;workflowMode=draft</value>
      <webElementGuid>bcce6f5b-6ec2-4b35-817e-c85865550735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mode</name>
      <type>Main</type>
      <value>diagram</value>
      <webElementGuid>26b6b3db-1b71-408c-94e3-f35c947b330d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Diagram</value>
      <webElementGuid>aa15a300-1ced-469b-9cc6-cc0973a0cc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflow-diagram&quot;)</value>
      <webElementGuid>658b5453-177f-4ecb-b11c-4f0711185de1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='workflow-diagram']</value>
      <webElementGuid>b10c645f-0b1d-42ef-8219-b62b5149fc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='workflow-links']/div/a</value>
      <webElementGuid>13494fd0-29a5-4c56-8386-0f8c53e13dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Diagram')]</value>
      <webElementGuid>7748ca14-5fb6-4993-a462-9ddd59777bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='you'])[1]/following::a[1]</value>
      <webElementGuid>171db34e-5373-45a2-8c16-a920a76354b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Original'])[1]/following::a[1]</value>
      <webElementGuid>710b8fbc-b820-4523-8567-0ac20d934c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text'])[1]/preceding::a[1]</value>
      <webElementGuid>ed229084-2377-4336-9dc7-14da44765638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/preceding::a[2]</value>
      <webElementGuid>fc56e0f4-a62f-4e2f-bbb7-3078890f2400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Diagram']/parent::*</value>
      <webElementGuid>9bdfcee7-f7cf-4fa7-bf4f-3bf93f46286b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/secure/admin/workflows/WorkflowDesigner.jspa?wfName=Software+Simplified+Workflow+for+Project+POK&amp;workflowMode=draft')]</value>
      <webElementGuid>ba4b3397-85d2-4199-83df-66a5f8abe03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/a</value>
      <webElementGuid>1abb9ea0-283d-4f47-8bd6-47e72d657af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'workflow-diagram' and @href = '/secure/admin/workflows/WorkflowDesigner.jspa?wfName=Software+Simplified+Workflow+for+Project+POK&amp;workflowMode=draft' and (text() = 'Diagram' or . = 'Diagram')]</value>
      <webElementGuid>535e9772-1988-47e6-960b-dd200a114234</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
