<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Workflows</name>
   <tag></tag>
   <elementGuidId>57252926-e475-469b-b024-2d3e45e1f07a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflows</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='workflows']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51300918-e92a-4bf7-8fe9-431c8824b7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/secure/admin/workflows/ListWorkflows.jspa</value>
      <webElementGuid>109aa6fd-8fe9-4cab-acae-815c55f849cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflows</value>
      <webElementGuid>0e4d174a-1faf-4d46-9f15-d17ae16be815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Workflows</value>
      <webElementGuid>15aa343f-e149-4810-9b1b-445aac6a2dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflows&quot;)</value>
      <webElementGuid>3c56e168-2847-42df-887d-82aba16c6208</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='workflows']</value>
      <webElementGuid>d0b6ade9-06fc-4151-a13c-cd40e0118979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/section/div[2]/div/div/nav/div/div/div/ul[2]/li/a</value>
      <webElementGuid>1a770fa1-1c47-4c2c-8444-3f5adcde5c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Workflows')]</value>
      <webElementGuid>7f9772fa-db74-4fec-b252-30a712c4ca42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workflows'])[1]/following::a[1]</value>
      <webElementGuid>4b8cb818-34f3-4a83-9bad-8ce312c91564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub-tasks'])[1]/following::a[1]</value>
      <webElementGuid>f39f89dd-7123-426b-b612-b277a5882d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workflow schemes'])[1]/preceding::a[1]</value>
      <webElementGuid>91ab0334-2548-4686-bd2f-b6d4685cab33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Screens'])[1]/preceding::a[2]</value>
      <webElementGuid>76d3e2b0-3138-47ad-9e8b-2235350829b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/secure/admin/workflows/ListWorkflows.jspa')]</value>
      <webElementGuid>1f82bf50-68f6-4728-b575-873677fd871f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a</value>
      <webElementGuid>39571f4c-d522-4c01-91c2-708ab9723619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/secure/admin/workflows/ListWorkflows.jspa' and @id = 'workflows' and (text() = 'Workflows' or . = 'Workflows')]</value>
      <webElementGuid>3cf8abee-9309-4998-84a5-ed92af274713</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
