<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TestIssue</name>
   <tag></tag>
   <elementGuidId>326300a3-ed53-48b6-818b-4f7cac7800c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[18]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a31416d2-da71-47f1-8fae-ccad56f028ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30761b0f-c924-448a-bcc2-5a063b446560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1vo3lvt</value>
      <webElementGuid>70f84150-1801-486f-a1dd-bc97e1b2fb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TestIssue</value>
      <webElementGuid>e062ebe0-0fd4-4614-9d0a-c39c2c74ea22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jira&quot;)/div[@class=&quot;atlaskit-portal-container&quot;]/div[@class=&quot;atlaskit-portal&quot;]/div[@class=&quot;css-194d9bm&quot;]/div[@class=&quot;css-1b3xg7v&quot;]/div[@class=&quot;css-hhgyfa&quot;]/button[@class=&quot;css-1vo3lvt&quot;]</value>
      <webElementGuid>e25f690a-5e99-4c06-a1f0-8fa4d70985dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[18]</value>
      <webElementGuid>9c3691a4-9f81-4020-89a4-7d6cdd4e3977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='jira']/div[2]/div[2]/div/div/div/button[6]</value>
      <webElementGuid>d69f2b58-eee3-4d2e-a12b-9e73385b9751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Epic'])[2]/following::button[1]</value>
      <webElementGuid>4d2c9c77-8207-4bc4-94c7-04bab752bc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bug'])[2]/following::button[2]</value>
      <webElementGuid>3311d984-e32f-4989-817f-40de9b8387b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]</value>
      <webElementGuid>060d9713-55cb-4e5f-af85-4991e0c11c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'TestIssue' or . = 'TestIssue')]</value>
      <webElementGuid>1ec94026-8582-41f1-bbb0-e799c3870622</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
