<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Only users with Create Issues permissio_be3290</name>
   <tag></tag>
   <elementGuidId>797cb762-99fd-4803-9df9-d36d88e0f9ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.condition-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='jira']/div[2]/div[2]/div/div[3]/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed3996de-b80f-4ee3-a0be-c4cec5670382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>condition-block</value>
      <webElementGuid>025b5189-755b-45e2-bd36-6d1471c3f80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Only users with Create Issues permission can execute this transition.</value>
      <webElementGuid>4375a80c-ec47-4efc-a06f-35b57428894e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jira&quot;)/div[@class=&quot;atlaskit-portal-container&quot;]/div[@class=&quot;atlaskit-portal&quot;]/div[@class=&quot;css-12p1yy3&quot;]/div[3]/div[@class=&quot;css-79ym8r&quot;]/div[@class=&quot;css-1yfnrso&quot;]/div[@class=&quot;css-e6hn7k&quot;]/div[@class=&quot;css-6g97ak&quot;]/div[1]/div[2]/div[1]/div[@class=&quot;sc-fBuWsC vPdpw&quot;]/div[@class=&quot;sc-fMiknA kdMXvS&quot;]/div[1]/div[@class=&quot;condition-block&quot;]</value>
      <webElementGuid>81583be4-0e19-4899-be3b-5aa3f4d0c4a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='jira']/div[2]/div[2]/div/div[3]/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>4cfc96a2-9b7c-4855-802f-7c8ab45d3078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>e148afc7-b4da-47cd-9b29-5ed95a556d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Only users with Create Issues permission can execute this transition.' or . = 'Only users with Create Issues permission can execute this transition.')]</value>
      <webElementGuid>517555da-0fdb-4b3f-9a18-b47ea4c437ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
