<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Skip</name>
   <tag></tag>
   <elementGuidId>9935e2f5-9705-41b2-a903-b378f11cb7a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='jira']/div[2]/div[2]/div/div[3]/div[2]/div/div/div/div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6670ccf0-0e78-4568-b598-6b3671fbe4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19r5em7</value>
      <webElementGuid>286bea89-e4bd-45d4-8d50-8ad101b67122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skip</value>
      <webElementGuid>d1c11259-77d0-4c33-a25e-2fda62b00c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jira&quot;)/div[@class=&quot;atlaskit-portal-container&quot;]/div[@class=&quot;atlaskit-portal&quot;]/div[@class=&quot;css-1ua1xqz&quot;]/div[3]/div[@class=&quot;css-1oc7v0j&quot;]/div[@class=&quot;css-1yfnrso&quot;]/div[@class=&quot;css-e6hn7k&quot;]/div[@class=&quot;css-6g97ak&quot;]/div[1]/div[2]/button[@class=&quot;css-1e2j28g&quot;]/span[@class=&quot;css-19r5em7&quot;]</value>
      <webElementGuid>ab73263b-cb62-447b-8b1e-00d78e75a8bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='jira']/div[2]/div[2]/div/div[3]/div[2]/div/div/div/div/div[2]/button/span</value>
      <webElementGuid>224b258b-63e8-41e3-a16a-57b8530c2bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Glass Documentation'])[1]/following::span[1]</value>
      <webElementGuid>c68a0798-f7c8-48b4-b5a7-2718d3cd8bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atlassian'])[1]/following::span[1]</value>
      <webElementGuid>55fe0e7c-afd9-432d-9a96-83447a26036d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::span[1]</value>
      <webElementGuid>364872ff-525d-434d-9af6-2bd12ea34570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Skip']/parent::*</value>
      <webElementGuid>9201e8a8-2c59-4832-9ccb-c04449e2b720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/button/span</value>
      <webElementGuid>e55c05d4-7336-473b-9e70-dca8d5b59cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Skip' or . = 'Skip')]</value>
      <webElementGuid>6f287102-923c-4841-9d18-38f7d4c382b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
