<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Validators 2</name>
   <tag></tag>
   <elementGuidId>137f2d32-9a70-4118-bbd6-1efc6b14239c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='jira']/div[2]/div[2]/div/div[3]/div[2]/div/div/div/div/div[2]/div/div/div/div/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ce423ae-4735-4094-81a5-773282ef141e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validators 2</value>
      <webElementGuid>14ccf5a8-bae6-4bfd-87fe-482730684fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jira&quot;)/div[@class=&quot;atlaskit-portal-container&quot;]/div[@class=&quot;atlaskit-portal&quot;]/div[@class=&quot;css-12p1yy3&quot;]/div[3]/div[@class=&quot;css-79ym8r&quot;]/div[@class=&quot;css-1yfnrso&quot;]/div[@class=&quot;css-e6hn7k&quot;]/div[@class=&quot;css-6g97ak&quot;]/div[1]/div[2]/div[1]/div[@class=&quot;sc-fBuWsC vPdpw&quot;]/div[@class=&quot;sc-dVhcbM KPvEY&quot;]/div[@class=&quot;sc-eqIVtm gDrdIk&quot;]/div[@class=&quot;sc-caSCKo iqHOFz&quot;]/span[1]</value>
      <webElementGuid>6dc69eb2-0261-41d1-8957-a05b4e26ec80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='jira']/div[2]/div[2]/div/div[3]/div[2]/div/div/div/div/div[2]/div/div/div/div/div[3]/span</value>
      <webElementGuid>02f3acfb-fda9-407b-b9b6-d40d50989398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POK: Scrum Default Issue Screen'])[1]/preceding::span[4]</value>
      <webElementGuid>f0de91c2-89a3-4fed-b10e-acecf38afc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/span</value>
      <webElementGuid>61616f26-9618-462a-a40b-b7c03307496a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Validators 2' or . = 'Validators 2')]</value>
      <webElementGuid>fb1c66e3-d358-411c-ab44-ceef23fedf60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
