<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Create</name>
   <tag></tag>
   <elementGuidId>a38ebcc5-3d4e-4dfe-b575-e1b84ad5dc0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div/div/div[3]/div[4]/div/div/div[2]/div/table/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2f9df60d-9b61-45dc-a0dd-8a9a67651416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eNQAEJ bcZAtY</value>
      <webElementGuid>6a6a8df0-5815-494e-8181-98aaf6c70d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>7216153b-3d19-4a10-8794-e1d1e5efff64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[1]/div[1]/div[3]/div[4]/div[1]/div[1]/div[@class=&quot;transitions-table-holder&quot;]/div[@class=&quot;sc-hSdWYo cwkwWt&quot;]/table[@class=&quot;sc-kGXeez dEUNvf&quot;]/tbody[1]/tr[@class=&quot;sc-hMqMXs iHbMkC&quot;]/td[@class=&quot;sc-eNQAEJ bcZAtY&quot;]</value>
      <webElementGuid>2d0b752b-e269-4b44-b824-834bdd14f073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div/div/div[3]/div[4]/div/div/div[2]/div/table/tbody/tr/td[2]</value>
      <webElementGuid>9f57e76f-5abb-47b7-b04a-ad117d7f481d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Functions'])[1]/following::td[2]</value>
      <webElementGuid>6c68f57b-d014-4d90-b52c-c9485252df5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validators'])[1]/following::td[2]</value>
      <webElementGuid>56b896ae-9a4f-44bb-8289-50b6cbecd91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPEN'])[2]/preceding::td[1]</value>
      <webElementGuid>a791b526-a922-4d5f-9051-16e52997307f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>113559b7-db88-4a5f-b452-e26347ec2e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>24b5ed9d-4e7e-46eb-bdf5-7672f1012417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
