<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Issues</name>
   <tag></tag>
   <elementGuidId>c8b9b79c-daa6-4d59-a25b-c8f98da6799b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin_issues_menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='admin_issues_menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8ef61aa9-17b3-4ea1-9ba2-df226c494a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/secure/admin/ViewIssueTypes.jspa</value>
      <webElementGuid>69c05661-4723-4f98-b4c2-83ec146eb6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aui-nav-link</value>
      <webElementGuid>f1e0bc14-9a98-40fa-9cf9-be27b4281c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin_issues_menu</value>
      <webElementGuid>e819cc09-94b9-4177-b2b4-c22f1caf36bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>56d9e3d2-5586-4a5a-a055-3880534f9312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Issues</value>
      <webElementGuid>692b4c11-a4db-41db-9630-a1e6ee112e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admin_issues_menu&quot;)</value>
      <webElementGuid>a827d83e-6b85-471b-acb1-df84bff683c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='admin_issues_menu']</value>
      <webElementGuid>80d9812d-5cf7-4284-b04b-2d2e7abed44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='system-admin-menu-content']/div/ul/li[3]/a</value>
      <webElementGuid>8a9ca68e-288e-457c-bf37-5ef0ac8c0aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Issues')])[2]</value>
      <webElementGuid>98dc31a6-3b18-4a08-9736-6953ebec041a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[2]/following::a[1]</value>
      <webElementGuid>973d9746-2236-4fbb-a267-9170c36599ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications'])[1]/following::a[2]</value>
      <webElementGuid>e21c4b3d-0d8f-47cd-b610-6ac4f18cc7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage apps'])[1]/preceding::a[1]</value>
      <webElementGuid>e9826617-6a5b-426e-8c31-b95649471bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User management'])[1]/preceding::a[2]</value>
      <webElementGuid>c14b9e10-5476-4e99-8e86-b49e83c417ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/secure/admin/ViewIssueTypes.jspa')]</value>
      <webElementGuid>02bc2f6c-43cb-4d5f-8c52-8fbb35904d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/ul/li[3]/a</value>
      <webElementGuid>240954fa-9dbc-4641-a209-671387c63751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/secure/admin/ViewIssueTypes.jspa' and @id = 'admin_issues_menu' and (text() = 'Issues' or . = 'Issues')]</value>
      <webElementGuid>ba55cec8-eeb3-4aab-bd6d-c53275a0b4ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
