<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Administration</name>
   <tag></tag>
   <elementGuidId>de810abe-cc3d-476c-9bac-56f4f6625c44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.aui-icon.aui-icon-small.aui-iconfont-configure</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='admin_menu']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b255c5eb-dc61-424b-8f1c-e9ec2f3a98ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aui-icon aui-icon-small aui-iconfont-configure</value>
      <webElementGuid>f82a9840-d519-4fca-9aa9-dba7b7fcfbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administration</value>
      <webElementGuid>37977cc6-3ef8-4f54-ac96-1918a583b3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admin_menu&quot;)/span[@class=&quot;aui-icon aui-icon-small aui-iconfont-configure&quot;]</value>
      <webElementGuid>2fa22bcd-d9c7-48ae-a30d-a657e17d2029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='admin_menu']/span</value>
      <webElementGuid>852d4ce5-705d-45c7-aada-502c68d91636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jira Credits'])[1]/following::span[1]</value>
      <webElementGuid>a0a6525d-5ed3-4b54-9105-31e8ff55a3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Jira'])[1]/following::span[1]</value>
      <webElementGuid>bdcf2e05-5a4b-432a-a51f-2feb0036d57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jira administration'])[1]/preceding::span[1]</value>
      <webElementGuid>d0e416fd-eec2-4a72-bb8d-b231b0c64b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications'])[1]/preceding::span[1]</value>
      <webElementGuid>ccc2e8e3-c871-4a24-8692-c5c6fa0d9aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administration']/parent::*</value>
      <webElementGuid>c99e2014-0580-4651-8cad-8c5f99dbe7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>de08e5af-7a2b-4b03-b685-51879ee88856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Administration' or . = 'Administration')]</value>
      <webElementGuid>44acb085-a70c-4f4c-88a5-23c422bc9dc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
