<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_webSudoPassword</name>
   <tag></tag>
   <elementGuidId>7efde491-c2bf-4a40-8fa2-735b15af3fe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-form-authenticatePassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-form-authenticatePassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04aa6e0e-b03f-4184-9c58-ea87a0e2c251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text focus-visible</value>
      <webElementGuid>3bea27d7-5eb7-420e-b211-28d3dac86c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-form-authenticatePassword</value>
      <webElementGuid>5014b57a-4db9-4c5c-9df6-789d30d3745e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>webSudoPassword</value>
      <webElementGuid>d8b82d69-73d3-4b7b-a43c-802b8d279fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e2a6e145-54a9-4633-a735-92e0f7cb2422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form-authenticatePassword&quot;)</value>
      <webElementGuid>b972f7d1-f7e5-415a-a2c6-2b0dd26daf15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-form-authenticatePassword']</value>
      <webElementGuid>09578a54-eaa9-4590-bf33-923add120561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/fieldset/div[2]/input</value>
      <webElementGuid>cd922902-2668-4b7b-b278-851daa648b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/input</value>
      <webElementGuid>1d902257-1648-4d8c-ad27-f74aecb17402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-form-authenticatePassword' and @name = 'webSudoPassword' and @type = 'password']</value>
      <webElementGuid>35eca26a-a946-4d2d-98e8-410b301a863a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
