<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PokeTestProject (POK)</name>
   <tag></tag>
   <elementGuidId>77b58e33-5b07-4fd5-9b7b-8ee6c81fb1c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin_main_proj_link_lnk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='admin_main_proj_link_lnk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0d62522-2cab-4585-b788-05ba3f1748a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/browse/POK</value>
      <webElementGuid>c18897bf-64a0-43c1-b8ac-1ac67141f054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin_main_proj_link_lnk</value>
      <webElementGuid>0956dbc1-f1aa-4014-92e9-d1dd2163ec10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aui-icon-container</value>
      <webElementGuid>3c150fa1-b7ac-41ad-9a3d-41b2a0dad2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iconurl</name>
      <type>Main</type>
      <value>/secure/projectavatar?pid=10117&amp;avatarId=10600&amp;size=small</value>
      <webElementGuid>25345979-39e4-4da6-8afa-8f89289b5601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PokeTestProject (POK)</value>
      <webElementGuid>6d397c35-6d47-40f9-97c5-0aa021bf454a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admin_main_proj_link_lnk&quot;)</value>
      <webElementGuid>f765c75b-0844-4020-9635-ab0d2d6660a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='admin_main_proj_link_lnk']</value>
      <webElementGuid>3bfb36de-9079-43df-ae1f-452b2f1f9768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='admin_main_proj_link']/a</value>
      <webElementGuid>4966592c-a56a-45b0-9c98-20356486f928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PokeTestProject (POK)')]</value>
      <webElementGuid>46964348-8679-49b7-8644-258e9af8dbb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Project'])[1]/following::a[1]</value>
      <webElementGuid>e3052fce-1297-41ec-a731-e941d8ee9981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[1]/following::a[1]</value>
      <webElementGuid>25b0c172-d514-410c-b31f-50373ed147e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Projects'])[1]/preceding::a[1]</value>
      <webElementGuid>d12991d0-6ad7-49c7-b2bc-2b2ebcb71ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JiraTestFest (JIR)'])[1]/preceding::a[1]</value>
      <webElementGuid>f33fec97-7d6c-458a-b099-7ff180e0cbe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PokeTestProject (POK)']/parent::*</value>
      <webElementGuid>70d0aab6-1142-4109-b41a-7bd37b1b8e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/browse/POK')])[2]</value>
      <webElementGuid>712e7189-93a3-402d-9df2-7c131ebfda64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/ul/li/a</value>
      <webElementGuid>2d38bac7-e04a-4b6b-8bd1-92b19deee005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/browse/POK' and @id = 'admin_main_proj_link_lnk' and (text() = 'PokeTestProject (POK)' or . = 'PokeTestProject (POK)')]</value>
      <webElementGuid>0569b481-a197-4a02-b8b9-aa8e94a85882</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
