<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add transition_show-transition-labels</name>
   <tag></tag>
   <elementGuidId>99273790-d948-4658-bfb7-c3b69eebb51e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show-transition-labels</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show-transition-labels']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a0af62f-3ae8-4179-bda7-71e601e34088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>27f3544c-0922-494b-8ca7-397bf7fe5288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4b9c4c27-d989-4ae1-b353-88cb7972f0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>show-transition-labels</value>
      <webElementGuid>9cc55832-5ef6-45e9-8374-057d5db80543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-transition-labels</value>
      <webElementGuid>05e2ac9e-64fe-481b-8500-38efdd210c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-transition-labels&quot;)</value>
      <webElementGuid>56fde496-92a5-4033-b431-068fe89cc582</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show-transition-labels']</value>
      <webElementGuid>6c2e8759-1c67-4c12-a5fa-0b27838ade83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='workflow-canvas']/div/div/div/div/div/fieldset/div/input</value>
      <webElementGuid>cba5760c-e0ea-437d-bd1f-454e9f6a1d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>2d9f75f1-f8e0-4a0d-b004-96c779f736d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'show-transition-labels' and @id = 'show-transition-labels']</value>
      <webElementGuid>78ef3e59-b730-46f3-ad24-c517a7c3691a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
