<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_Create</name>
   <tag></tag>
   <elementGuidId>4926645f-ebf3-4103-a562-d50c2d957175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tspan[(text() = 'Create' or . = 'Create')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>6c2f9e5e-bd9d-49ff-a7c1-9f4373bbdb64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5e9cf424-e927-4635-a13f-0ba0d254419c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>4e58c8e7-f538-442c-8510-d219a8c10d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflow-designer1&quot;)/svg[1]/text[7]/tspan[1]</value>
      <webElementGuid>84f2da05-051d-489c-92a1-619c6cda20ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tspan[(text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>cc44034e-47f4-421d-98d9-2061eab51f46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
