<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_Rejected</name>
   <tag></tag>
   <elementGuidId>e2f28c5f-9c5c-46ab-92a0-4c9e8369dd40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Rejected']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>3359858a-4712-49cf-b23c-cb17939a382d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b1a09e59-d2f3-4769-a52a-952ba2117f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rejected</value>
      <webElementGuid>74e93660-736b-4899-946e-546bf0230051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflow-designer1&quot;)/svg[1]/text[11]/tspan[1]</value>
      <webElementGuid>e42b671d-dd07-4e6b-ac89-f099172fd219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rejected']/parent::*</value>
      <webElementGuid>5e1a3a85-1b2f-450f-962c-b889a97820ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tspan[(text() = 'Rejected' or . = 'Rejected')]</value>
      <webElementGuid>fa80f354-26a3-47f7-9590-b284a79b6605</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
