<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>37d5cd53-ea2b-42c9-b88e-5558d78512eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='edit_live_Software Simplified Workflow for Project POK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba1f902e-518f-482e-a1b5-e47d042fdb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-operation</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>00c71035-4a94-4f66-8276-3bd6da8d9532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_live_Software Simplified Workflow for Project POK</value>
      <webElementGuid>21b2d2e1-3d93-4d4c-a00f-10361784b7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>EditWorkflowDispatcher.jspa?atl_token=BHU3-2U44-WUNY-74BF_1fab58a07d0564d9bd5945a4acbdeb104ccef38e_lin&amp;wfName=Software+Simplified+Workflow+for+Project+POK</value>
      <webElementGuid>050a7f18-35f3-413b-9ded-e8b88572e6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickonce</value>
      <webElementGuid>efae2fb1-7220-4055-a515-11ed16484873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>4a4c63a8-5186-4dee-8a0f-9563ce472506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_live_Software Simplified Workflow for Project POK&quot;)</value>
      <webElementGuid>2a14b0dd-1f8f-4546-a087-f39858b22ee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='edit_live_Software Simplified Workflow for Project POK']</value>
      <webElementGuid>e9522569-3df8-4c2a-b102-97152e5bf633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='active-workflows-table']/tbody/tr[15]/td[5]/ul/li[2]/a</value>
      <webElementGuid>803125c9-fae0-4de5-965c-9b8aba394072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Edit')])[14]</value>
      <webElementGuid>4d662f88-a881-4979-8cbe-7c888297b48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[15]/following::a[1]</value>
      <webElementGuid>3e6d28bd-8d7f-4f6c-bff1-a643318ddf15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POK: Software Simplified Workflow Scheme'])[1]/following::a[2]</value>
      <webElementGuid>bfe6231a-8985-4c2a-91c4-b5819356ca52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[15]/preceding::a[1]</value>
      <webElementGuid>ab75be9b-3e6e-4c13-8bdc-9d24d56c6aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software Simplified Workflow for Project TES'])[1]/preceding::a[2]</value>
      <webElementGuid>7479e175-8dba-47d4-860d-161b67474f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'EditWorkflowDispatcher.jspa?atl_token=BHU3-2U44-WUNY-74BF_1fab58a07d0564d9bd5945a4acbdeb104ccef38e_lin&amp;wfName=Software+Simplified+Workflow+for+Project+POK')]</value>
      <webElementGuid>4cbdceab-b947-45e6-a3a9-48e7a647ac2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[5]/ul/li[2]/a</value>
      <webElementGuid>aea376e9-9a81-4505-8f03-9e5d2a62a3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'edit_live_Software Simplified Workflow for Project POK' and @href = 'EditWorkflowDispatcher.jspa?atl_token=BHU3-2U44-WUNY-74BF_1fab58a07d0564d9bd5945a4acbdeb104ccef38e_lin&amp;wfName=Software+Simplified+Workflow+for+Project+POK' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>874f214b-aa4f-49be-a942-0f90932d1085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
